spring:
  application:
    name: employeeapp

  datasource:
    url: jdbc:h2:mem:employeeapp
    driver-class-name: org.h2.Driver
    username: employeeapp
    password: employeeapp

  h2:
    console:
      enabled: true