spring:
  application:
    name: employeeapp

  datasource:
    url: jdbc:h2:mem:employeeapp
    driver-class-name: org.h2.Driver
    username: employeeapp
    password: employeeapp

  h2:
    console:
      enabled: true

  security:
    user:
      name: othertwink
      password: admin
    max-failed-attempts: 5

logging:
  level:
    root: error
    org.othertwink.employeeapp: DEBUG
    org.othertwink.employeeapp.security.filter: DEBUG
  file:
    name: logs/application.log

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:employeeapp.p12
    key-store-password: employeeapp
    key-store-type: PKCS12
    key-alias: employeeapp
